---
title: "HW3, Lecture 5"
output: pdf_document
date: "2026-02-07"
author: Isaac Pinto 605956560
---

```{r}
library(ggplot2)
library(ggfortify)
library(dplyr)
library(corrplot)
library(GGally)
library(leaps)
library(car)   # for VIF
library(caret)
library(tidytext)
library(textdata)
```
```{r}
num_vars <- train %>%
  select(where(is.numeric)) %>%
  select(-SalePrice, -LogSalePrice)


cor_matrix <- cor(train_split %>% 
                    select(where(is.numeric)),
                  use = "complete.obs")

sale_cor <- abs(cor_matrix[, "LogSalePrice"])
sale_cor <- sort(sale_cor, decreasing = TRUE)
sale_cor
top15 <- names(sale_cor)[2:16]   # exclude LogSalePrice itself
top15
top25 <- names(sale_cor)[2:26]
top25

subset_formula <- as.formula(
  paste("LogSalePrice ~", paste(top25, collapse = " + "))
)
best_model <- regsubsets(subset_formula,
                         data = train_split,
                         nvmax = 15)
best_summary <- summary(best_model)

# Find model with lowest BIC
bic_values <- best_summary$bic
best_size <- which.min(bic_values)
best_size

best_vars <- names(coef(best_model, 15))
best_vars <- best_vars[-1]  # remove intercept
best_vars
#items_to_remove <- c("Qual_x_Area", "MiscVal")
#best_vars <- best_vars[!best_vars %in% items_to_remove]

final_formula <- as.formula(
  paste("LogSalePrice ~", paste(best_vars, collapse = " + "))
)

m0 <- lm(as.formula(paste("LogSalePrice ~ BsmtQual + LogTotalBsmtSF + I(log(X1stFlrSF)) + OverallQualSq + Location + SentimentScore + Age + LogGrLivArea + GarageCars + I(log(LotFrontage)) + Log_LotArea + TotalBath")), data = train_split)

m0 <- lm(as.formula(paste("LogSalePrice ~ I(LogTotalBsmtSF^2) + I(LogX1stFlrSF^2) + OverallQualSq + SentimentScore + Age + LogGrLivArea + GarageCars + LogLotFrontage + Log_LotArea + sqrt(TotalBath)")), data = train_split)
 
mmps(m0)

summary(
  powerTransform(
    cbind(SalePrice, TotalBsmtSF, X1stFlrSF, OverallQual,
          SentimentScore, Age, GrLivArea, GarageCars,
          LotFrontage, LotArea, TotalBath) ~ 1,
    data = train_split,
    family = "yjPower"
  )
)
```


```{r}
engineer_features_basic_location <- function(df) {
  road_rail_conditions <- c("Artery", "RRAn", "RRNn", "RRAe", "RRNe")
  sentiments <- get_sentiments("afinn")  # scores words -5 to +5

  sentiment_scores <- sapply(df$House_Review_Text, function(text) {
    words <- data.frame(word = unlist(strsplit(tolower(text), " ")))
    score <- words %>% inner_join(sentiments, by = "word") %>% summarise(s = sum(value))
    ifelse(nrow(score) == 0, 0, score$s)
  })
  df %>%
    mutate(
      SentimentScore = sentiment_scores,
      # Age since built or remodeled
      Age = ifelse(YearBuilt < YearRemodAdd,
                   YrSold - YearRemodAdd,
                   YrSold - YearBuilt),
      
      # Basement finished area
      BaseLivArea = TotalBsmtSF - BsmtUnfSF,
      LogTotalBsmtSF = log(TotalBsmtSF+1),
      LogGrLivArea = log(GrLivArea),
      Log_LotArea = log(LotArea),
      LogX1stFlrSF = log(X1stFlrSF),
      LogLotFrontage = log(LotFrontage),
      OverallQualSq = OverallQual^2,
      TotalBath = FullBath + 0.5*HalfBath + BsmtFullBath + 0.5*BsmtHalfBath,
      TotalSF = X1stFlrSF + X2ndFlrSF + TotalBsmtSF,
      TotalFinishedSF = X1stFlrSF + X2ndFlrSF + TotalBsmtSF - BsmtUnfSF,
      HighQualitySF = X1stFlrSF + X2ndFlrSF + TotalBsmtSF - LowQualFinSF,
      GarageCarsFactor = factor(round(GarageCars),ordered = TRUE),
      
      # Road/rail proximity (either condition column)
      RoadRail = factor(ifelse(Condition1 %in% road_rail_conditions | 
                        Condition2 %in% road_rail_conditions, 1, 0)),
      
      # Neighborhood location tier
      Location = factor(case_when(
        Neighborhood %in% c("MeadowV", "Edwards", "Sawyer", 
                            "Landmrk", "SWISU", "BrDale", "IDOTRR", "NAmes", "Mitchel", "BrkSide", 
                            "NPkVill", "OldTown", "ClearCr", "Gilbert", "SawyerW", "NWAmes", "Crawfor", 
                            "CollgCr", "Blueste", "GrnHill", "Blmngtn") ~ 1,
        TRUE ~ 2
      ))
    )
}

engineer_features_simple <- function(df) {
  road_rail_conditions <- c("Artery", "RRAn", "RRNn", "RRAe", "RRNe")
  sentiments <- get_sentiments("afinn")  # scores words -5 to +5

  sentiment_scores <- sapply(df$House_Review_Text, function(text) {
    words <- data.frame(word = unlist(strsplit(tolower(text), " ")))
    score <- words %>% inner_join(sentiments, by = "word") %>% summarise(s = sum(value))
    ifelse(nrow(score) == 0, 0, score$s)
  })
  df %>%
    mutate(
      SentimentScore = sentiment_scores,
      # Age since built or remodeled
      Age = ifelse(YearBuilt < YearRemodAdd,
                   YrSold - YearRemodAdd,
                   YrSold - YearBuilt),
      
      # Basement finished area
      BaseLivArea = TotalBsmtSF - BsmtUnfSF,
      LogTotalBsmtSF = log(TotalBsmtSF+1),
      LogGrLivArea = log(GrLivArea),
      Log_LotArea = log(LotArea),
      LogX1stFlrSF = log(X1stFlrSF),
      LogLotFrontage = log(LotFrontage),
      OverallQualSq = OverallQual^2,
      TotalBath = FullBath + 0.5*HalfBath + BsmtFullBath + 0.5*BsmtHalfBath,
      TotalSF = X1stFlrSF + X2ndFlrSF + TotalBsmtSF,
      TotalFinishedSF = X1stFlrSF + X2ndFlrSF + TotalBsmtSF - BsmtUnfSF,
      HighQualitySF = X1stFlrSF + X2ndFlrSF + TotalBsmtSF - LowQualFinSF,
      GarageCarsFactor = factor(round(GarageCars),ordered = TRUE),
      
      # Road/rail proximity (either condition column)
      RoadRail = factor(ifelse(Condition1 %in% road_rail_conditions | 
                        Condition2 %in% road_rail_conditions, 1, 0)),
      
      # Neighborhood location tier
      Location = factor(case_when(
        Neighborhood %in% c("MeadowV", "Edwards", "Sawyer", 
                            "Landmrk", "SWISU", "BrDale", "IDOTRR") ~ 1,
        Neighborhood %in% c("NAmes", "Mitchel", "BrkSide", 
                            "NPkVill", "OldTown", "ClearCr", "Gilbert") ~ 2,
        Neighborhood %in% c("SawyerW", "NWAmes", "Crawfor", 
                            "CollgCr", "Blueste", "GrnHill", "Blmngtn") ~ 3,
        TRUE ~ 4
      ))
    )
}

train <- read.csv("HousePriceTrain.csv", row.names = 1) %>%
  mutate(LogSalePrice = log(SalePrice)) %>%
  engineer_features_basic_location()
test <- read.csv("HousePriceTestNoY.csv", row.names=1) %>%
  engineer_features_basic_location()

set.seed(5)
train_index <- sample(1:nrow(train), 0.8*nrow(train))
train_split <- train[train_index, ]
valid_split <- train[-train_index, ]


# Best model (too many betas):
model_initial <- lm(as.formula(
  paste("LogSalePrice ~ BsmtQual*I(LogTotalBsmtSF^2) + LogTotalBsmtSF + I(LogX1stFlrSF^2) + LogX1stFlrSF + OverallQualSq*Location + I(sqrt(SentimentScore+2)) + Age + LogGrLivArea + GarageCars + LogLotFrontage + Log_LotArea + TotalBath")
), data = train) # 0.90200 (use train and remove bad leverage)

model_initial <- lm(as.formula(
  paste("LogSalePrice ~ BsmtQual*I(LogTotalBsmtSF^2) +LogTotalBsmtSF+ I(LogX1stFlrSF^2) + OverallQualSq*Location + I(sqrt(SentimentScore+2)) + LogGrLivArea + GarageCars +  Log_LotArea")
), data = train) # 0.86856


########################################
# Code to remove bad leverage:
########################################
# Calculate hat values and standardized residuals
hat_values    <- hatvalues(model_initial)
std_residuals <- rstandard(model_initial)

# Identify bad leverage points
p <- length(coef(model_initial)) - 1
n <- nrow(train)
leverage_threshold <- 2 * (p + 1) / n
bad_leverage_idx   <- which(hat_values > leverage_threshold & abs(std_residuals) > 2)

# Remove bad leverage points and refit
train <- train[-bad_leverage_idx, ]
model <- lm(as.formula(
  paste("LogSalePrice ~ BsmtQual*I(LogTotalBsmtSF^2) + LogTotalBsmtSF + I(LogX1stFlrSF^2) + LogX1stFlrSF + OverallQualSq*Location + I(sqrt(SentimentScore+2)) + Age + LogGrLivArea + GarageCars + LogLotFrontage + Log_LotArea + TotalBath")
), data = train)
########################################
# END
########################################



final_model <- model_initial
summary(final_model)
autoplot(final_model)

anova(final_model)
vif(final_model)

pred_log_valid <- predict(final_model, newdata = valid_split)
pred_valid <- exp(pred_log_valid)

cor(valid_split$LogSalePrice, pred_log_valid)^2
cor(valid_split$SalePrice, pred_valid)^2

train_control <- trainControl(method = "cv", number = 10)

model_cv <- train(
  final_formula,
  data = train,
  method = "lm",
  trControl = train_control
)

print(model_cv$results)  # gives you mean R² across folds

```

```{r}
pred_log_test <- predict(final_model, newdata=test)
pred_test <- exp(pred_log_test)

NN<-1:3000
Sub<- data.frame(NN,pred_test)
names(Sub)[names(Sub) == "NN"] <- "ID"
names(Sub)[names(Sub) == "pred_test"] <- "SalePrice"
head(Sub)

write.csv(Sub,"./Sub1.csv",row.names = F)
```



